### ISSUE TITLE
数据库

### ISSUE THREAD

**Issue by Dkingo** [TuoJihu/StrayAnimals#15]
老哥数据库不是sa吗，怎么给了beam

**Comment by TuoJihu** [comment]
加我qq 1289024322

**Comment by Dkingo** [comment]
@TuoJihu 老哥，显示拒绝被添加，你加我吧835464016

**Comment by OldQi** [comment]
你好，我也需要数据库，可以加我吗？急！！qq：392272248

**Comment by Dkingo** [comment]
> 老哥数据库不是sa吗，怎么给了beam

**Comment by OldQi** [comment]
> 老哥数据库不是sa吗，怎么给了beam

你好，你拿到了数据库了吗

**Comment by TuoJihu** [comment]
加我微信 18221096962


| |
tuojihu
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年5月26日 ***@***.***> 写道：

老哥数据库不是sa吗，怎么给了beam

你好，你拿到了数据库了吗
